# Generated by Django 3.0.2 on 2020-04-20 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0030_auto_20200420_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 19, 47, 2, 325895)),
        ),
    ]
