# Generated by Django 3.0.2 on 2020-04-21 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0033_auto_20200420_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 2, 19, 7, 576991)),
        ),
    ]
