# Generated by Django 3.0.2 on 2020-04-21 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0052_auto_20200421_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 16, 35, 41, 622088)),
        ),
    ]
