# Generated by Django 3.0.2 on 2020-04-23 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0056_auto_20200423_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 23, 16, 59, 8, 701671)),
        ),
    ]
