# Generated by Django 3.0.2 on 2020-04-24 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0057_auto_20200423_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 10, 6, 39, 381831)),
        ),
    ]
