# Generated by Django 3.0.2 on 2020-04-24 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0058_auto_20200424_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 15, 43, 16, 420927)),
        ),
    ]
