# Generated by Django 3.0.2 on 2020-04-24 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0059_auto_20200424_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 15, 53, 18, 184647)),
        ),
    ]
