# Generated by Django 3.0.2 on 2020-05-02 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0060_auto_20200424_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 21, 0, 11, 965050)),
        ),
    ]
