# Generated by Django 3.0.2 on 2020-05-02 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0062_auto_20200502_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 21, 32, 9, 375675)),
        ),
    ]
