# Generated by Django 3.0.2 on 2020-05-03 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0074_auto_20200503_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 20, 47, 5, 477137)),
        ),
    ]
