# Generated by Django 3.0.2 on 2020-05-03 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0077_auto_20200503_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 21, 4, 4, 569435)),
        ),
    ]
