# Generated by Django 3.0.2 on 2020-05-03 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0080_auto_20200503_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 21, 32, 58, 896407)),
        ),
    ]
