# Generated by Django 3.0.2 on 2020-05-04 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0084_auto_20200503_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 9, 52, 45, 697034)),
        ),
    ]
