# Generated by Django 3.0.2 on 2020-05-06 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0088_auto_20200506_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 6, 17, 28, 57, 613207)),
        ),
    ]
