# Generated by Django 3.0.6 on 2020-06-04 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0090_auto_20200508_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 18, 23, 27, 679588)),
        ),
    ]
