# Generated by Django 3.0.2 on 2020-05-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20200502_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=2.99, max_digits=1000),
        ),
    ]
