# Generated by Django 3.0.2 on 2020-05-04 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cartitem_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='notes',
            new_name='variation',
        ),
    ]
