# Generated by Django 3.0.2 on 2020-04-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200421_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'CATEGORY', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['update'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
