# Generated by Django 3.0.2 on 2020-04-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200421_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='media/rzultypeep.jpg', upload_to='media/products/'),
        ),
    ]
