# Generated by Django 3.0.2 on 2020-04-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200423_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'ADDITIONAL IMAGES'},
        ),
    ]
