# Generated by Django 3.0.2 on 2020-04-23 14:59

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200423_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-update'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'ADDITIONAL IMAGE', 'verbose_name_plural': 'ADDITIONAL IMAGES'},
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='media/rzultypeep.jpg', upload_to=products.models.get_upload_path_thumb),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(default='media/products/szlugson.jpg', upload_to=products.models.get_upload_path_thumb),
        ),
    ]
