# Generated by Django 3.0.2 on 2020-04-24 08:06

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200423_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='doggo.png', upload_to=products.models.get_upload_path_thumb),
        ),
    ]
