# Generated by Django 3.0.2 on 2020-05-03 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200503_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='category',
            new_name='var_category',
        ),
    ]
