# Generated by Django 3.0.2 on 2020-05-03 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200503_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='var_category',
            new_name='category',
        ),
    ]
