# Generated by Django 3.0.2 on 2020-05-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200503_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('size', 'size'), ('shoe_size', 'shoe_size')], default='size', max_length=120),
        ),
    ]
