# Generated by Django 3.0.2 on 2020-05-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200503_2107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationManager',
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('universal', 'universal'), ('size', 'size')], default='size', max_length=120),
        ),
    ]
