# Generated by Django 3.0.2 on 2020-05-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20200503_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'ordering': ['-product']},
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('universal', 'universal'), ('size', 'size')], default='universal', max_length=120),
        ),
    ]
