# Generated by Django 3.0.2 on 2020-05-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20200503_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('shoe_size', 'shoe_size'), ('size', 'size')], default='universal', max_length=120),
        ),
    ]
