# Generated by Django 3.0.2 on 2020-05-06 13:38

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20200504_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(default='media/products/szlugson.jpg', upload_to=products.models.get_upload_path),
        ),
    ]
