# Generated by Django 3.0.2 on 2020-05-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20200506_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
