# Generated by Django 3.0.2 on 2020-05-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20200506_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('shoe_size', 'shoe_size'), ('skate_size', 'skate_size'), ('size', 'size')], default='universal', max_length=120),
        ),
    ]
