# Generated by Django 3.0.6 on 2020-06-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20200508_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('size', 'size'), ('shoe_size', 'shoe_size'), ('skate_size', 'skate_size')], default='universal', max_length=120),
        ),
    ]
